<a href="https://colab.research.google.com/github/niteshsah3424/Application_Development_Lab-AD_LAB-/blob/main/week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import zipfile
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
import os
os.getcwd()

'/content'

In [ ]:
os.listdir()

['.config', 'sample_data']

In [ ]:
from google.colab import files
files.upload()

Saving spambase.zip to spambase.zip

{'spambase.zip': b'PK\x03\x04\x14\x00\x08\x00\x08\x00\xb9\xb2\xb6V\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x16\x00\x00\x00spambase.DOCUMENTATION\xb5Xmo\xdb\xc8\x11\xfe\x1c\x03\xfe\x0f\xd3\x00\x81\xedBb\xf6\x95\xdc5p\x1f\\\'\xd7\xcb!N\x0eI\xae\xfdP\x14\xc1\x9aZKD(R\xe5K|\xbe\xa2\xf7\xdb;\xb3K\xcaZ\x19\xc1\xe1\n4\x01\x12\x8a\xday{\xe6\x99gH\xf1\x0c>UC\xed/\x01>\xfetu\x03\xaf\x97[W\xd5\xf0\xca\r\xee\xd6\xf5\xfe\xf4\xe4\xf4Dd\xf0\xb1\x1d\xbb\xd2\xf7\x97\xa7\'\x00p\xee.\xe0\xba\xf3nh\xbb\xfe\x12n\\\xf7\x05~hw_\xaa\xa6_\xc0\xeb\xae\xfa\x02\x1f\xbc\xbf\xf5\xdd\x02\xfe\xea\xdbn\xed\xe1\xfb\xb6\xdb\xbaf\x01?:\xb7\x83\x8f\xa3\xef\xb6m\xb3\x1a\x82\xab\xf0\xe7\x07\x7f_\xfbaX\xfe\xe4\xca/\xae[\xc1[w\x8b\x9e\xb8f\x1c~rh\x7fS\xd55|Xe\x0b\xfcX\xb7pU\x0f\xed\x02\xae\xaf\xc0*\xc9T\xcc\xe8\xf6\x02^\xb5M\xdb]\xa61\xe1|}\x17/\xdc\x00M\xdb\xef\xdc\x166\xbb:\xdb\xec\xb2\xb2\xdd^\x00\xe4\x9a-\x8d.\x96\x85\x91:z*/\xd0E\xe3;7\xf8\xd5%\xfc86~\xf9\xe3X?\x00\xb7\xd6\x12\x182\xc3,\xfa\x01~\xee1\xb5G<\x8ekx\xd3\x0c\xbek\\\xbdl\x1b4\xfe\xe4\xcbMS\x95\x0e\xcb\xf0\xbb\xb6\x1b2x\xfdK\xfc\x1e0\xbfa\x83\xc9T\xcd:{\xac\xc5\xe3\xb7x\xcb\xc3\xfd\xc6\x0f\x1b\xdf\x81\x83u\xf5\xd57\xe0Cw\xaa\x1eB-m\x87U\r\xd9>\xf3\xdf\x8a\x17\xb0\xad\xfa\xb2v}_\xdda\xc0\xa1j\xd1\xa6\xeb\xda.\xdb\xe3\xfd\xbd\xab{\x0f\xbb\xb6\xaf\x06t\xd9\xc3\xf9\x16;\x88\xe1a\xdd\xb6+\x08\xfe]\xf4\x7f\x01\xae\xf3\xf0\xd5w\x0f06+\xdfW\x9d\xbb\xad\xfd\xa3\xa77wp\xef\x01\xfb^! \x18\xe8W\xdf\xb5pw\xe4\xbej\x00+\x80\xa1sU\x83Q^\x0e\xbe\x1f(Z\xef\x87\xc5\xde\x93`K\xa1_@{\x17\xce\x86\xdavX\x83_\xe1\xe7\xae\x1d\xd7\x9bp\xff\xae\xaa\x11\x97\x8c\xda\xa02\x84\xb2\xf6_]3 \xd6\xa1\xc9T\xeb\xe5#\xab>\xa1\xc1s\xf2\xf4\x1c\xca\xb6)\xfdn \xd8V\x98S\xd7#\xdb\xdd\n/\x86\xaa\xf7[\xdf\x0c=\xb5\x01v]\xbb\x1a\xcb\xa1\x7fy\xefo\x1f\xfd`\x1d\x1e\xe9\xb8u_< q\xfd\x03V\x88\xe5\xf6\xe5\x06M\xf1\x8br\x83\x85\x015\x1f\x1d/\xb0\xf0\xaei\xd7\x9d\xdbm\x1e\xb2\x0cS}\xf6~\xec0\x81\xba\xf6eh\x06\x96\x18\xca\xf3a\xcez(\xdd\x16\x0b\xebZl&\x1eD\xd8\x86-\xba\xa7\x8e7+@\xf3\xaa\xc1\x94\xab\xd5\x88\xa8"\x19Z\xd8\xb8\x15\xe1\x80\xc8\x90\x9b\x0c\xe0\xa9\xff\xa6m\x96!\x06\x9a?\r\x13\x8d\xef[\x9cZ\n\xb1\xc3\xac["\xe2tr\x11\xeen<"\x86\xe6\x84:\x1e]\xc1\xd9:\xcc\xd5Y\xf8\x96\xee"3\x1c\xc6]y8\xc3!:\x0bL\xa1\\\xcb \x0b\x94\x06\x9a\xcf\x99d\xa1\x1d}\xb0\x82\xb1\xf7wcM\xccn\xa83\xfd\xd0!\xe8\xc4\x08\xb7O\xa6\xfa\xd5\x87\xe2C\x15S\xd7\xb1R\x9a\x87v\xacW\xe0\xab0\x14\x1b\xf7\x15\x89\xd5\xc2m\x8d\x91\xa1\x1f\xcbMR\xfba:\x1d\xac\xfd\x80\x11\x02\x99\xef+L\xfb\x1b\x98\xa1;4]O\x12@s\x17.k\xd8\x8d\x1dvg"\xe7\x01\x13g\x9e\xa0\xe2\xc0-N\xff\x1a\xf9\x8a\xd9\xa0[:y@\xc8\xeb\xce\xa1B-\xe0m\xdbu\x15*\x14\xea\xd9[w\xe3\xcarS\xb9\x05\xfc\xa5\xabP\xa6\xae\xb0\xcc\x8fh\xf6\'8\xb0k\xb7\xdb\xb1\x99\x86\xb9\x9fg\xe4\xea\xfaf\x01\x8a\x9f\x9b\x8b\xcbB-\x8d\\\x90B\x99\x90\x91\xce\xe0\xdd\xb8E\x05\xa6\xb3o\x10`\xd7\x90v\x83\xcaQQ\xcf\xb9\xe12\xc4\x80\xef@\xdaL\xbd\xb8 \x9b\xfc\xd0\xe6j\x18\xba\xeav\x1c\xc8H\x1b8\xd7\x055\n{4\xb6#)3\xa2\x85\xe2\x84\x98\x04\xa1\x81\xda\xdd\xfa:x)\xb2G\xdb\xa3\xb1\xa4q\xacip\x10\xf7q\x1b0?#\x80h\xc9d+\xdc6g\xb0\xf2(f\xbe\xdfk\x1e\x95\x19Y\t\xf7\xa8H\xa7\'\xc4\x16l]7\x91\x1fk\xb9\x98$\x10\xce\xd9\xc5\x02\xaa\xccg\xa8T}[W%N\xed\ncm\xb7\xbe+\xab=\xbd\x11\xde\xd3\x93\x9b\x96\xe4*\xc2\xe8\xf6\xa5\xce\xec=\xd4\xdc\x9dC\x89(\xc7\xdauq\n\xda\x0e\x93\xd8\xb8\xce\x954\xa1\x94\xd4]\xe7\xff5\xa2\x82\xa0\xc8\xb7e9v\xc4\xe3I\xf1\xf6\x11\xa9\xf4nl\x96\xb5o\xd6\xc3\xe6\xf4\xe4 \xe6\xb9\xd6K]\\\xc0\xd6\xbb~\xc4\xd9 \xbbx,\x08E\xf0\x8d\xbd\xa3\x0fT\xbc/G\x12U\x82\xc2\xed\xaa\x01\xcb\x9at\'\x8b\xfc\x0b\xe29 \xe4(\xb1\xb4m&\xb7\xc1\xde;\x1c\x8f}\xe8\x05\xfa\xe8}\x0c\xe8\x89\xae\x04\x07\xea#\xa9CF+\xb9\x8b\xc3J\xdf\xaf\xfc\x1dJw\xc2\xbe\xc7\x12.\x83\x1a\x9b\x03\x82\x00*C\r\xff`\x0b\xce\xd8?\x0f\x01&\xdb\x87]\x14\x94\xcf\x04\xdc\xe7\xbf\xbf\xff\xf0\n\x13\xf9\x8e\x06\xbfD\x14i\xdb\xe3):\xd0\xa70\xe2%\xaepd\x13\x16AV\xb8:B\xb71\x06\xfc\x19\xce\x9b=w\x87\nU9\x18\x06\xe7n\xb7\xf3\xae;rv\x01/1\xea\xd0\x12\x80\x8f\x96\xfb\xa8\xfb\xc6]\xc1s\xba\xf9<ZW\xa4\xa2(\x00\xf8\xbfk\x1e\x08\xbf!\xb4\x1bM]\xbd\xdb8\xf4\xe4\xbb\xaa\x84=Az\xb8%)@\x1e\xde>\x04\x81I\x8e\x1d0)\xe8\x13va\xd9\xde-\xa3\xd30\xc7\xf9\x1f\x01\x95\x9cEP\xaf\x7f\xb8\xfa\xf0\x14\xd3\x83`\xdf\x04\x96,\xbf\t,}\x199\x1e(I\x18F\x04S\xcf\xd1+\xa5\xcf\x9f\xa6\xcf\x17\xb8\x13\x0f\xd2\x7f\xcc>\xd2\xf93\x8e\xc9\xe7\xc8\xff\xcf\xa8\xed\x1d\xe6N\x95L\x97\x07\x93\x81zH\x0fX\xdd\xb8\xa31O\xe7$\x9d\x8c\'\x99\x90\xe1\x1aK\xfaC\xc9\xd4m\xb3\xc6\xe7\x16J\xe61\x89\xe9\xe67\x92\xf9\xbf\xe5\x12P\xa7L\xfaq\x1b\xd2\xf8\x9fP\xf9\x0e\x8e\xf9\x7ft$\xa5IL}\xd6\xfd\x7f#\x0f\xff3\xa9\xff\xd3\x9cI\x9b)\xc0\xef\xe8\xf9\xef\xa9\xf9D\xc4\xdf\xd7s\xfak2|M\xc0\x87^\x9c\xc7\xc7\r\xf47W\x8f\xb4\xc3\xde\xe1c\x1b\x1d\xb2\x19\\\x87\x9c_U}<\x13w\xd33Z\x87\xcf\x00\xc2j\x84\xf3y+>C\xbbe\xd8\x94 \nc\xf0\x9b\x9cey\xdc\x97\xa7\'\x8fa>\xce\x8a;\xbd\x1f\xddT\r\xbd\x16\xfd\x82\xafTp\x15\xa9KoW\xc3*{\xe5\xbf^\xe2>\xf7ww\xd9\xdfp\\_\\\x02\xa1\n\x8c\xd6\xbc\xca\xb4\xc2\xffX\xc6\x99\xd2:\\I\xa6e\x8e\xc1\xad\x80\xfd\x1f|\x1d\x9b\x0c\xb8\xca\x84\xa1c\x82K\\\xecx#\x13\x96\xe1y\xc8\xc3\xbf{\x039\x19\xe8\x8cN\x91\x81ay\x1e\xae4S\\Q\xe1\xec\xd0@\xcd)\x89\xccPz\x19\xcb\xb5\x12\x9a"H\xab)\x19\ny`\xa0\xe7\x94\xe2M\xcc\x9c\x0b!\xc2U^\x08\xcd\xc9@\x1fF\xc8\xf7)\x11\xae\x14\xc1j\xcbB,QH\x83\xa6\xc2$5\x14\x93A\x81\xdfG\x94\xb8\x12<\xc6\xb2\\a\xc6R\xc9C\x033\xa7\xc4\xf1h\x84U\x0b\x1b\x0c\x14\xe3\x0c\x9dH\xc3\x0f\r\xec>%\x91O)1\x96\x171%\x93cJ\x92\xd9C\x03,6F0\x19\x8f}\x90V\xc5\x94r\xa5\nj\\\x9e\x1a\xf0h \xb2<\x1ec\xda\x1a\xa1\x82)\xe3\xd4})\x8b\xc4@D\x03\x9b\xe5\xb1h\xadx\x11\x016y\xb8\xe2:\x8d \xe7\x1a&\x061+\xad\x9c\xb8\x84\xbc\xc2\x08"\xe946?m\x1c\xd3Xj\x1e\x0c\xa4\xa6\xb2t\x91\x90\x0f\xdb8\xb1u*\x95)+\x98\x0e5hc0\x82\x16I\xe3x>\x15=G\x10\xca\x98\x98\x9c\x11\xba\xb0Tt\x1a\xa1\x98;\xcd\xa7y@\xeaM\x8dS\x8a\x98-y\xd28\xccrB\x89\xc5c\xdc\xa8"\x9aj<\x1a\xb8\x94\xc2j\xf7\x8d+\x02\xa9\xf3<P\t\xaf\x8a"\x00\x17\xf8q0q\xc7\x9dfF\xeb\xa2\x88\x03d\xe9B\xdb\xa4h\xc1\x8f\xc8g\xf0X\x1eG\x941\x13\x86\xd7$\x06S\xa7y\x91EX\xb9\xe0"\xa6\xc4\x10W\xbc0*\x8d\xb0\xef\xb4\xd2\x93j\xf0|R\r\xcd\x88\xe8R%\x13\'\xe6N\x8bl\xa6\x86\n\xfc$XE\x8ex\xa9"\xa1\x86\xd0s\xe32##\xf9\xac\x8e)\xe5\x05\xe9$\xce\x83J\x0c\xa6N\xf3<\xcb\x03\x83D\xaee\x9cncr\x02H\xca\xd4`\xea\xb4\x94H6:V\xe4E\x98a\xfc\x1c\xaf\x94L\xe8-\x9et\x1a\xc94w\xda\x10LJ&\xd4\x10\xf6H*\x995\x96\x07\xb6j+)h\xce\x92\xa2%;\xd2%\xce\xc4\xc4V\xa5\xf3\x9c"\xa8\xa4\x06\xc9\x8fa\xcdU\xa1e\x94\x19I\xe9\xe7"\xd1%)\xe6\x01*&\x99A\xdcUHNb(\xbc\x97\xdb\x84\x1aR\x1e\x93\xcf\x16B\x84\xc6i\xad-\x7f2\xa2R=\x8d`\xa4\x8e\x11,\xb1"7\t\xacR\x1f\x8d(J\xe54\xddZ\n\x1ag\xcd\x12.\xc9|\x1e\xd1\xdcN\\*T\x9c\x07\xc5\x04I\xa5\xe2i\xd1S\xa7\xf3\xccL\x8d\x93\xb9\x9d`\x15\x81\xa8G\xda*\xa7N\x9b\xc0\x0c\x8a\xc0Q\xb9\xe2~\x10\x8c\x88\xce\xf3\xe2p\x03I{4q\x8c4;\xd2[*\x92O\xad\x93\x94\x14;F)WF\x061\x96\xca\xd2\xc6\xd5*]\x8a\xfcH\x97\x98\x92y\xdc\x0f2\x0f\xc3jD\xa2\x1aJ\x1c\x91\x0fK\x90\xd1\xb4@*Q\x84")ZM\x9d\x96\x99.\xa6\x089\xb36\x16\x1d\xb6\x95J\x97\xa2RG\x8dc\x85\xe56\xcc\x1e*\x1a\xd1\xa80I\xe3\xd4\xdci\x8e\xb8O[!\xeci\x94\x19\x1e\x16\x8a\x94i\x84Y\xbdE\x16E\x9e\x17\xd6\xc4\xc5ny\xd0V\x9dJ\xa5*\xe6\x1d\xc7\xa7\x1a\x90K\x8a\xe2br\xb9@]\xe6\x8a\x1d6N\x99\xe3\r$\xb9\x89\xba\x84\xe3@*`l\x1a\xc1\xce\x8d\x93FG\x03<\x177\x10\xb6\x1a\xcf\xe6\xa9\x08h6\xabF\xa1E\xec\x83e\x91U\xa2`T/\xb7\xc9Lk>G`\xd3\xe3\x0f\xcf\x83|\xd3d\xd80\xd3\xa9\x08\xe8\xa9\xd3Rd8jA\xf9,\x8b\xe5\x1b\xae\x89#\x92%\xe4\xd3r\x9e\x07\xc6dl\x9c6\x91\xb7Bi\x92\x1e)\xd2\x08\xb3z[\xdc\x9a6P\x03\x07\xc7\xc4\x01\xb2\xc4*[\xa4Ek\x88+\r\x05\x0c\x95\t\x1f\xfdl|\x02\x93\xb8\xe4\xc2sP\x9enQT\x9e\xf0\xd9\xda0\xa2\x9a\x1a(cH\x15\xa7V\x16iJ\xc5\x14A\x1b\x12\x0bad\x16\xfc\xd2\xd3gFr\x83,K\r\xe6N\xc3\xfc\x90h\x15\x8b\xf3\x80\x8f\x04\xe1i&-\x9a\xfe~\x9a\x7f\x94\xb8<\xf8\xb9\xe8\xd5\xfb\xeb\x9fo^\xbf\xfbt\xf5\xe9\xcd\xfbwg\xf4\xdb>\xbdZ\xfc|\xfd\x06\x9f\xba\xcb\r\xfdl\xfe\x16_\xfa\xe9\xd7\xe6\xf0{{_\rm\xf7pz\xb2\x19\x86\xdd\xe5\xcb\x97\xf7\xf7\xf7\x19>\xabgc\x89\xef\x17\xab\xf1\xe5o\xdb\x9aN\xbf\xbcy\xfbx8\xdb\x0c[|\xe7\xf9/PK\x07\x083\xc1\xfa=\x97\n\x00\x00\x1d\x19\x00\x00PK\x03\x04\x14\x00\x08\x00\x08\x00\xb9\xb2\xb6V\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\r\x00\x00\x00spambase.data\xec\xbdi\x8e\xe3\xb8\xd26\xfa\xff\x02\xdfN\x0cA\x9c\xc9\xfdo\xec2F\x06)\xc9\x93\xb2\xaa\xb3\x0e^T\xb7m\xc9\xb2S\xd6@\xc6\xf0\x0c\xfbc\xdfr\xe4\x87\xfe\x14<<\x8d\x7f\xbc~\xbc\xe76\xdf\xfaC\x0b\xb8\xaa\xe5y\xf3O\xffm\xa5T|\x15\xb6\x92\xf2#\xbb\x87\xef+\xdc\xff\xfb\xff\xf6\xcd\xbb\xfe\xb6\xef\xefn\t\xb7tQ\x96\xf1\x9d\xbd\xd0\x0eDYQ\x1a\xecm\x92E\xdc\x1c\x1f`K\xf8`\xd8b\xc1\x1f\x90\x1a~4\x06~\xb8\xdc9\xfa\x1b\x17o::T[(\x1e\x96`\xc7\xf6X\x1fis\xfd\xaf\xba\xdd\xf5\xff=\xff\x94=\xd3out\xfc\xe0\xef\xba\xa6\x0f^N\x81\x87\x9d\x0f\xf0E1\xf1\x1b}\xf3\x02\xaf\xe1\x1b\xe0\xc1m{\xe8\x0f!\xf3\xe9\xd8\x12}\xa7\xe3\xf7_\x1dn\xd9\x84\xbe||/\xbfK\x07\x8eN\xad/\x19\x7fW\xa47\xdaV\xfbq\x8d5=\xbc\xef\x07\x10~\xd7\xb8F\xe8\x13\xc1\xf1\xeb\xf5\x95>\xe8fx\xc6]\xb5\xcb\xdf]?.\x14\xfb\xdc\xbf5\xf5W\xb1\x1f\x93\xe6~\xd1N&\xfb|\xb9\x93n\xabi~\xf1\xc3\xff6\xef\xc7\xf5\xde/\xa4\xf4Hq\xde\x81\xe6\x97{\x1fnq\x87\xf7\x1d\xaf\xa4[\x1e\xae\xbe\xc0{i\xc6\x88/viO4\xf28\xfck\xb4\xe4\xb6\xdco\x96\xbek\xfd2\x9d\x8fO\x9d_\xfc\xf8\xf11\xf7\x90\x87\xdb\xd0\xf5\xdd\xa0\xab}s\xf4c#\xfd\xfe\xec\xe80\xd01\x81[\x11\xef\x17|h~>\xfd\x89\xeez8\xed\x0f?V\x9e\\(\xa7g}\x0b\xeb^\x16\xfa\xe3\xae\xe2\x18\xb9\xc35\xbc{\xdf\xef\xd1\x12\xe3#\xc2n\xfbT\xc6\xd8CcL\xe1;\xa5\xc9\xd8\x11\xea<&\xe8 \xa4\xe3\x03\xbd\x80\xb3!c\x85\xfc\xe5\xf6\xc9\x19\xcev\x01\xcf2\x0f1\x11\x17*\x8da\xa5O,}\xec)q\x1e]\xec<C\xd7\xe7a\xd6\x81\x15\xfdb\x8c\x1fMIO6\xec\xe7\xd8\xf3\xdf\x0b\xfd\xf7\xe7\x87\x1f\xb7\xa9\x1c \x1c\xa7q\xc4\xf6i\x9c?o\x1f\x1e\xe3\xbau<\x03\x94\xefo\x13\xef\xf1\xe8\xd1\x8f\xcc4\x9a\xc1u\xd5\x0fY\xbfHa\x9c\xa6]\xdc2\x9e`\x9e\xce\xe3:\x9d\xb7qU\xd1\x9d\x16Z\xbf\xd2\xf7\x86\xaf\xf7{72\xff\xc8\x9aeJ\xef\xc3\x06L\xe9y\x19\x8a\xdbx\xa4\xe7y\r\xdf}\xc5\x1fV~\xfb\xaf\xff\xc0\xda\xaf\xacG?U\xbc#n\x8b^\'\xe5\x8d\xc7g~\xe2k<\xc8yM\x9b\x8e\xdb\x10Z\xf4o\xabi\xde\xe2\xe3\ta\xe7\xd8!\x15\xb9\xae\xfb\x1f\xf5\xf1\xe1w\xd9C\xdc?\xda\xc9~\x92\xe9\xd6\x8drU\xfa2]]^\xbe\xa5\xd0Fc\x03\xf9\xc8\xd9\xbf\x97[\xf5\x1b\x97\xee\xd3\x84!\x0e-\xa5\x1ec\xb5G\xeaa\xc0r\x9fb(\xf6\xe4\x8f\xe1\x88\xdd\x0f]\xb89DG\x9e\x8bb\xdf\x91>\x07A\x9cU\x0e\x03\xc6\xd3k\xc1\xd1\xf9\xfd\xfa^\xc4\xd3\x85\xb1\x1a|EH}\xb8\xe8\xf1QzDs\x9do)\xd1\x8d/#\xf5<\xf4x\xb3\x16\xbf\x06\x1e\x82L1\xcd\xdf\t6*}yL\x12K\xf4\xc1>>\xca\xae\xe3\x83\x0c\x1d\xa9\x9dD<\xe6}\xb8<4@\xc2H\xc8o\x9e.\xc8\xe6\xe6`j\xf9\x8e\x93#\x96\xda\xf9\x84[\x12\x0f\x1ep@#\x8e\xc9}\x9e\xec\xe3\x11\x84F}$\xf9\xe0\xcc\xde\xcaC|\xb3\xcf0\x9d\x84\xf0\xe8Cc\xe0i4I&\xc1\x17\x0f\x06\xce\x89\xe7\xecm\xf7r\xcaq\x03\xcc4\xb6\xdd\x9b\xd1\x1b\xc3?\x1ei\xfb&\xfd\x80\x14\xfe\xe1O\x07}\xf9\x83\xe7o\xe3\x18\xe10l\xdf1\x05\xc0\ti\x8f\xb4s0\xb0\xa7>\xe0\xe7|\x88\xd9\xfd\xd5\xdd\xea\x9f\xdf\xc6o\xdf\xa48\xcdG\x9aO\xb6\xba7\xbee+\x84%\xfd\xae]\xa2N\xb7N\xe8\xa9\xce\xef\xe1\x93\xbe.\xe9V0\x1ex\n\x95Q\xd3\xf5\xcb6=r\xfb\x93\xd7Z\x9fo\xa2\xdd\t\x89\xa21\x9e\xa1%\x18G\xe0L=\xaa\xff\xd7\xaf\xb9\xc4\xd7\\\xfde\x87t\xfat\xbe\x8a\xff\xc2\x16\xc2\xf9\xc2\xa7\xd7Z\xc8\x95\xef\xaa\x0c1Z\x1f\x87\xdf\x98\xaa\xee\xfc\xc5\xf9\xaf\'o\x9f1\x9fz\x84\xbc\xa4\xc5\xc9<\xe9\xcbe\xd9a\n\x02\x8f\tf\x00\'\x19\x89\xd9\xec\xb3\xe1\x81K0;\xcd#p|j\x81k\xc6y\xbc\x0b\xfb=Y.\xce\xb9y\x83\x17\xfat\xe1\xbf\xba|\xd6\xbf\xd1C\x14M3`_\xfa\xf5\xa3cB\xe0\x9c\xe5\xe2\x8c\xed?y\xc6 B\xf1\xfc\xc5\xad\xdf\xbb\x90\x83\x86%\x0fn8w\xce{\xef\xcc\xac*u\x06\x8aW\xcb\xbc\xfe\xe3\xc8>&y\xd5\x9c$\r}\xaf\xea\x9bCf\x84\xa8/\xde\x0e\xfd\xe4 \xed\\\x18\xeb\x83\xb6+\x1a\xd5\x1c\n\x02\xb0\x8aJek.\x10\x1f\xf3\'\xf4\xa5\xbc\xb0\x1f\xa3u\'_\xb4\x86]I\xaf\x86\xea{>\xda\xffR\xd6i\x0e\x06\xc5\x17?,\xcd9\xe3wG\x86v5qU\xb3\x9f\xf8\x9eqf\x93\xf6\xfc\x95\xb9\x1f\xab\x93\x91\x8e\xd7VK\xe0k\xc0Af\xe2\x1f~\\4[\xa4\xfd\xe5\x92J\xac6D.\xe3\x0b\xab,{\xaa\xd7\xf2\xd3\xfc\x89w\xf6\xcc\xfe\x01*;\xc0\xca*\xa5\x08\x98/z,Pz\xa0\x1b\x9a\xe6aU?y\xf8{\xeb^\xd2\x1a\xfdA\xad\xdc8\x8c;\x7f\x1f\x87\xd7=\xfe\x86\\z\x84\xc4[t:\x89\xc1\xeb\xe5\xa7\xba\xe5%\xdc}~\xe3\x0b\xc4\xa7\xcf\xcf\xaa\x9b\x12C\xda\xb9"yqM0\xbd\xf5\x14\xb6\xd2\xa56JVX(\xa3\x8c\x06\x0bj\xa3\xa6\xe5\xa0\x1cf\x8b\\\x1e#\x9c\xa9\xb6\xc6/\xaf\xae\xf7\xa7\xd5\x08\xc7\x15\xbd"\x8f0\xb0B\xd9\xb2\xbf\xf0\xf9o\xde\x11!$y\x84\x9fD\xf5\x05\x98\x8e\xfb\xddP\xff\xea\x8e`\x96\x15\x92\xd49\xcew\xe4I\xeeJ}\x8e\xbf\x92\xbez\x99\x8b=L\x1e\x8f<\xc7\x92<\xe7o\xb0\xd5\xf4\xda\xac\x90\x95\x0e\x07_z\xd5\xbf\x9d\xee\x82\xcd\xe7;7\'\x8dj}\xce\xc5\xda+\x8ex\xae\x07w\xfd\n\xeb\xd7x\xa8\x8f\x10L\xd5\x18\x0b\xc9\x1cu\xcb=\xe0p\xbe\xde\xb2\xdeEX\x07\x0b\xd3u\x1d\xa9\x03\xe5h\x1a\x7fq\xc5?-&\xd3\x1d\x0f\xe5\xcc\xaa\xb7o\xea\xf3E\xbfk\xfb\xedPJ\xe4\x9d\xad\xe3\xc4R\xb6@\xad\xa6}~p^^A\xb5\x1e\xefS-"s\xa9\xa8\xef;\xbe\xe7#\xfcr\x8a\xf6\xa8\x95\xf4ny\x96\x9bfc{jO\xed|\xb2\xa9W\x95\xe9\xf8\x94\x1e1Ct\x1d9s\x8a\\O\xd4\x12\xe3\xa8z\xb6F\x0f\x9e\x07v\xc9La\xac\xa6\xed\x82LK\x8d\xfb\x84\xed\xdb\xbb\x8d\x1b\x1b\x92g\xc6~\xd8\xeb\xa3\xf1\xb1\xc6\x84)\x8c\x86\xc2\x9e\xf4\xc8&\xe9tb\x8b\xb2ho\x10\xf71e\xee!\xca\xdaH\xe5\x7f\xa8N\xfa1\x9d\xd2\xf5\xf6"j9I\xfd\xcc\xf1\xe7"\'\xfe\x91\x82\xb7\x90K\x90\x01T(\xcd\xb4\xd0\x07\xd2\xb8\x9b\xdf\x12\xb3\xb9\xab0\x87\xa1k$P\xee\x80?-\xc0\xd1/\x81\xdb\xb5\xf6\x9e\xa5\'\x8eXw\x99\xd7\xb0Y\xf1\xcd\x9d\xca\xf7\xe4\xceM\x01\xe8*\xef\xd4y\x85U}\xc2\xaa\xd8\x80\xab\x8d\x87\x15\xed|\xb9u\xf8\xbaZ!\r\x87\xdb\xa5\xe9\x92\xb0$\xc2\x85&<8!\xeb]\xa3\xc7+\xf0*n\xfer\xb2\x9bu\xa7\xa6\xf7<\x1c\xb9\xf1\x80\xc3M\xf8vD\xe68\xa9U<\x99\xf4\xdb}\xbf\xbb\xfb\xc8\xe1J\xfb3m\xa6\x9f\xef2q\xf7\xbd@54<J\xda\xe5\xc4\xfbq\x0c\xa7+\xcd\x9d]x\xba\xd2}rY\xce\x1b\xf7\xdfU\xc7\xf3\x96\xb8\xe8\t\x05\xc7>Vp\x1dJ/\x04z\xb5\\\x08\xee\xfa:p\xd3e\xe0\xf5\xff\x9b\xd7\x00]\x04\x14\xc7\x04\xbe\x04\x1a]\x02o\x14i\x1d\x87\xb3\xf2\xc2_%\xf8\x1f\x14\x7f\x189\x82\x01\x9d\xdb\xf3\xb1\xc0c\xbaYg\x0b\x81\x06\x19\xaf7\xda7\xa3\x0cF\xb7^{\xc2I\xd7\xc1c\xc0\xf9\x16\x8a\x081\x8f\xc6\xd3\xc9u\xe3\xa7Px\xacHoO\x97/*J\xb9\xcf\x8c}O\x9c\xe6\x0eI#\x11\x13\x94kufy\t\xe5~N\x80\xddG3\xcay\'`w6;\xedI\xc3\xbe\x9b\xa6\x97\xe3$\xfc\xd0\x942+\xa4y\xd7G`\xbf\xd1}\x9d\xeb\xe7)\xcd<\xdd\xf19\xcc\xa3\x01P8\xa7\xd1\xd6\xaamb\xe8\x82\xe0\x89\xa6\x0e\x87\x83 \xca\xddh\xf8j\xdc6\xbe\xa1n\xa9g\x7fP\xd0\x14H\x02\x87\x01\x91\x86K\x1f\xce\xbe \xe8\x13\xbd.|\xc0j\x9b\xb6x\xb7O\xe2\xcc\x18\x1b\xe4\x11\xa3\x1c\x89k}\xc3Bc\xce&\xcf\xcfR5\xc2\xab)\xf0\x83\xbe\xa7Kc#\xb3\x9a#\xa4Wg3_\xde\xa3mY\x82\xca1\xdc\x0fE\x9b\xad\xd2\'\x97kO\x0bB!.]tm\x9bC\xb0\x12)\xad-az\xf7\xd8u\x0f\xf1\xdd\xf1$\n\x8e\x0c\x878(\x1a\xa7G\xcb\x1c\x9d{\n\xa8\x15\x1aF\xd3\xeb<\x03\xf0\x94\xe1\x97\x02\x9c\xa32\xa5\x9bf\xddu\x90\xf7\x87\x97W\x9b\xeeR\xc0\xc5i~\xe7\x10\xa3\xb8\x88\xad\x9d\xcaa\xa1\xdeRkan\x9ef[\xe5\xdf\xb2<\xdd\t\xaa\xfc\x9e\x14\xc0E;\xe5\xdd\xb1\xa2s(=Q\x88=\xd5\x89\x0eo\xf5\x1dN\'\x05\xa5\xe3\x04\x95\x9fn\xa59d\xa2b.&\xf8\xd0!\xc3&A\x8b\xc7\xf9,\x16\xfbB\x97G\x01\xb1\xd6\xb3\xf5\x9f\x0f:z\'\xc3\xf9\x94\x1a+\xe7\xa6kA\x86\x109\xc1\xbe\xa0\x12\x1d\xce\x85\xb8u\xa2\xc9\xcc\xe9Hs\x9e\xc6^%\xb7v=\x8f]{\xc2\xbf\x93\x1cE\x92\x10\xceG\x18p\xc2\x1e>\xed8\xb9\xe7\x80\xa1\xe7o\xf7\xcb\xcc\x99\x1d\x83\x9c\x97\xe7\xfb\x05\xd7\xe7\xb3L\xea\x8e\xea\x10\xc7\x87q\x1a\xf7y\xe3\xc0\xb9\xd2\x9d\x13\xca\xe8\xc8\xd2\xbf\xb5\xcfg\xe5\xe1\x9bN\xb9x(\x13_\x8a\xe1\xf0\xc1\xf9\xa5#\x10j\x96\x97w\xca\x9b\x85\xeb\xc3\xd2\xab\x88T\xdf\xd4\x8a>\x86\xed\x95g\x83uD\x1d+\xf8%l\xe9qt\x84\xe1#~\x1e\x0c\xc4\xb3\xf2\xce.;Wa\xca\xc5``\x0c#y$\xef#\x01\x1e\xd3\xd0a\x99\xcbf\xcdK\xa5\xd3In\xf4\xf1\x04w\xf8D\x1f?\xaa\xe2;\xe1\xe6\xeb\xa7\t\x80a\xfb\xb1\xd8\x1eO\x8a\xedy)\xb6\xd3\x15\x18\xddx\xfa\xa9b;\xe6\xfb\x91\x82\xdb\xbe\x87Xk\xd7\x926\xa2\xb9\xd7J\xe7\xbcb \x88x==\xddB\x84\xc2lNG\xc0g\xb8A\xa0\x84\xe7\xea\x88\xd8\xcf\xa2\xb8\x05\xd0\x02\x8b\x11\xf1\xe6\x14\xfa]\xde\x89\xed\x9dl\x8bK/\xf8\xdc\x8f\x1dE\x19P\x88\x01\x14\x04G\xcb\x04\x0c\xc7z\x9e`\xa0\xeb\x00vs\xd1F0:\xf0Q,\xad0\xcc\xb9\x8c\xcam\xe4\x80\xc2\xe3Y\xdf0<\xe2\x82\x0c\xbe\xf5\x0clq\x8c\x13\x0e\x83B\xdf}\xfc\x11\x89\xd0\xf6X\x8c\x0fT\x08\x84:L\xee_\x0f\xd5\xd1=\xdb\xbe\xc6\xce\xf9*\x16\x04</J\xe2\xb6\xf1/\x94\xb6g\xe0\x05I\xe46\x02o\xf2\xd3G\r\x0e\xf9\xa8_Q\xfe\xb0/\tb1W\xd2{3L\x82\x83\x98nU\x99\xa7\x0eBe\xccB\x86\xae\xe7\xfe\xee,\x97\xe6Z\xfe\x9dt\x9b\xb1]\x11+)\xd0\xc4s\xd1\x80b\xc3\x92p\xc0}\x99\x8e\xc9\t\xe5!\xf8\x8e\xdf\xf87I\x1er\x1d\xb6\x98\xec\xe5\xfaB\xe44\xa41\xc4\xa5\xcf\x04}&\xed\x7f\xc2\xf7h49m\xe7a}\xda\x84\xc7N\xd3]\xbb\xd6\x0b\xc2\xadx\xb3\xc51\xb0\xfe\xa0\x82"\xb9Z\x93\xe8*\xf5\x9b\x12\xf1\xb1\xa32P\xe5\xc9"\xee\xe7:\x92\x00JR^>\xf2m\xbbE~g\x14(C?\xbdm\x01\x1c\xfcI\xe4\x9d\xa7:N\xbf\x8f\xa3\xf4\xc1\xc3\xc3\xf7(@G`3\x91\xf6s!\xd3_\x1f\xf1\xf3H\'\xcd|(o\x98\xb7\xf8c\xcfg\xdaW\x1bq\t\x11\xe0\xb08B9\n\xd8sx\xf4\x91\xcc\xbbq\xc0\xe4\xc2\xc6\x08\xb8\xe4\xf9F\xaeZ\x11\x1d\xa5Q\xb8J\t\x99\xed\x15Y\x13\xea\x97\x97\x997\x85)|\xc4\t\xac\xcfj\xfd\x85\x02\xb2^\x84\x94\xf0\xb6\x03\x10\x1e>\x04\x8a\x07\xdc@\xe5}P/\xb0\xb9\xb7\xe7\xec\xda+,\xaa\xf6c\x04\x01\xf0n\xd9\n\xf8\xc0\xc3\xc6\x08\xf3\xb48,\xcd\x05\'\x87JFh\xa2|a\xd4\xecN\x8b\xc2\xf9),\xf0\xb0U\x1fD\xb0\xc9\xc4T\xb3\xbd\xe51\x9daq\x0f"\xf4>G\xd6\x98\xbe\xbfY\xdag\xe5G\x87=\x98Q\xd8\x83\xf0\t\xfa\x8d\x12\xccg\xee\xb4\x8cX\xd8f\xf0\xd4\x08\x15(\n\xbc\xe8\xa7\x80pF\xe1\xcb*\xda\xb1\xc7\xb8\xe3\x8cLUb\xe8\xab\xf5i\x02\xa9N\xd2\xf7*\x12\x85\xc4b\x1a_A\x1b_Y#\x0f\xed\xe7R\xe3\xab\x8e\xc8D7\xc2:4]\x9c\xa6\xe9\x15?ID\x0cb\x92\xda\x06Y\x18N\xc4\xea\xc1\xab\xaa\xc7my\x93\xb6\x17\x1fo\x02P\xe3\xae2z\xd8I\xdb\x81\x1ep\x11\x0f9\x052M^\xa5&<@\xdc\x0e\xff\x10w) \x11\xa2s!9Y\x9b0\xd6\x876\xd7K\xe6b_`\xe0\x81\xa3T\xcf3_\xae\xf4\xc1\xa6\xf4o\xee\xf1n\xf8G\x7f\x10B`\xf1b:\xffA&=;\xa6N\x92~\xc1\xa8\xeb\xa6\x8c\xcdS\xc8\xcf\xeb\xdd[\x83\xf1\xd5\xac\x119M\xc10~\xab>p\xb2\x0b\x1d\xaf\xdd/5\xd2\'/u\x8e\xea\xf3[Y\xe6\xb7\x8f\xe2\xdc|Z0\xcb\xfdn\xebW\x86\x12\x12\x91\xdc\xc2}\xb8\x95\xe7\xa2\xd4\t\x055\x14\xa1U\xb8\xed\xf3\xd4\xdb~=O`\x10\xd1H@\x92C\x83()\xe8\x0ck\x99\xbb\x07\x02\xafY!\x9b\xd4L\xace~}\x03\x9b\xc2#V\xe1b+\xcc_\xd8\xc0\xf0+\xbcx3=E\xf78\xbeaWo\xf9\xbb\xd1\x16\x81M\t\x93\xbe\x887\xa6F\xe8\x15@hE\xd8\xa5\x8ej\xc6\x08\x17\xf3\xf1)\xb4K\xb1b\x80&(\\\xb4\x8b\'\x08\xb0O\xe1bB\x9dt\x08\xce!\xd4\xae\x83\x94o\xce#p\xef}\xba\xa0\xe7h\xea\x1f% \x89\xeen^U\xcd\xac\x1a\xb0\x93(\xf7c\x8e\x8f\xfd\t\xbbUV{\x93\xd2\xbf \xc2>y\xbb\x07\x018\xcdP)\x18\x812Y8\x88\x84\xd7\x01\x92\x82o\xfe\'\xa3\xf2g@\xf3-\xecT\xbfu\x9c\xab4\xc9\'\x01No{;\xffw\x9c\xfe\xef8\xfd\xe0q:\xc9\x1b\x8e\xabm*\xf2F*s\x8dj\xc0\x80\x93Jb\x18\x97\n\xf17\xf5\x8f\x05\xd83\x97\xeb/=D\xa35\xe1d8\\Z\x15\x81*\xce\xee\xb6J\x07\xfe\xcb8`\xe7\xfdQ\x0e\xad)\x7f\x16T\xf8\x0f\x03\x93\xe7M\x98\xbdh\x01$=\xca\xcaby~\x15\xf8/\x93\xe9\xe3\xcc\xaf\xb5!\xacP\xe4A\xe6\x11\xe42\'\xf46\xe9_\xfe8\xbc\xe7\x04\xb1Zn\x1f\xa1\xcd\x95\xc2\xfdX@,\xe4G?\x0e\xde\xad|\xebg%\\\xbc\xee\xb9V\xd7\xee\x10\xeb\x82!\x03A2P\x1f\xf9!b.\x08\xef\xc2|\x8e)\xc5\xb5j\xd9xK\xd2\xc5k\xbcP\xab\xad({\x15C\xf1\xb8\x05\xd6\xb2\xa5\xc4\x12.{\xd4O\x1b\xdc\xa6y\x1dP8\xc6qC\xdba+;\xf6e\x84\xf1\xa6\xc1-v\x9c)*\x18\xf7X\xdbw28\xd9|\xe7\xb3F\xdd\x1461\xaeDi\xdf\r\xaa\x91\x03M\xc4\xc9\xaeTI6\xa7\xd4>\xce\xa9G\xff\x94k\xe6B\xfc\xdb\xb0\x1d \x9f\xe6l\x8a\x06C\xf9\xf0\xfe\xd6\xa5p\xdcV\xc8B\xa4\xe4\xb19Gp\xaf\x9e\x9d\xf5Q(\xd5\xfa\x9b\xf7<\xe4\xd3=o\xb4\xeb\x0b\x05\xcbW\xa9\xc3\x8e\x8a\xed\xf2\xb0P{\xc6\xc6?\xc0\xf5\xd1\xabb\xf7\xd8\x15\x08;\x002G!(\t\x8e\xdfS\xe1|n\x01\x98\xf7y\xc9\xd3\x08\x1a6fx\xe5;\xdc\x15\x1f\xa5\x02J\x98Qj\x8eW\xe8\x9d`)(\xfd\xdf\xf5\xfb_]\xbf8\xc0\x12\xf6<\x8e?\xbe\x87\x01\xdaE\xd8\x7f\xd6]\x0cB\x01E9\x80]:1\x84}\n\xc2(\xe2/K\x8a\x1ey\x17\xa5mFc\x92\xf5*J\x99\x81[\x05K;}\xc4/=\xdf\xf5\x8f\xd4\xa0;;\n\x01X\xca\xe2\x1a:sR,\xe8FdW\xcc\x93\xbc\xaev\xf9\x10HO\x84\xf4\x03;\xfdI+\xc3q\xeb\t.\xa3\x06Q$\xd07\xfb\xab\xb6\x10\x90\x05\x0b\x10\x9es\x9b\x84\t\x95\xbf\xcas\x89\x94\xcdS\x89\x97\x8a&\xf4I{\x08\xd7wJ\xa5\xd6\xf8\x98\xe4b\x8a\xeb\x82\xdc\'\xd6\x06.\x12\xf8\xd7\xd0Q\xb4d\x0c\xab=!\x1e3\xf4\x0b\x04q\xf7\x06\x93\xf9\xe2\xe8\nj\xdd\xb5\xa1\n\xd5#a\x08\xb9v\xf7\xc8\xa2n\x94\x14\xaf\xe4\x96y\x19o\xb4\xdd-08\x06\xfe>\xa7\xeb\x9e^\xc1\xf3\x97\xf5\xcb\xbe\x8d\xe7\x1

In [ ]:
import os
os.listdir()

['.config', 'spambase.zip', 'sample_data']

In [ ]:
import zipfile

with zipfile.ZipFile("spambase.zip", "r") as zip_ref:
    zip_ref.extractall("spambase_data")

In [ ]:
os.listdir("spambase_data")

['spambase.data', 'spambase.DOCUMENTATION', 'spambase.names']

In [ ]:
import pandas as pd

data = pd.read_csv("spambase_data/spambase.data", header=None)

In [ ]:
data.columns = [f"feature_{i}" for i in range(data.shape[1] - 1)] + ["label"]

In [ ]:
data.to_csv("spambase.csv", index=False)

In [ ]:
data.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,label
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1

In [ ]:
X = data.drop("label", axis=1)
y = data["label"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=5000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=5000)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred) * 100, "%")

Accuracy: 92.29098805646036 %

In [ ]:
from sklearn.metrics import confusion_matrix

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[506  25]
 [ 46 344]]

In [ ]:
from sklearn.metrics import classification_report

print("Classification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.95      0.93       531
           1       0.93      0.88      0.91       390

    accuracy                           0.92       921
   macro avg       0.92      0.92      0.92       921
weighted avg       0.92      0.92      0.92       921

In [ ]:
results = pd.DataFrame({
    "Actual": y_test.values[:10],
    "Predicted": y_pred[:10]
})
results

   Actual  Predicted
0       0          0
1       0          0
2       0          0
3       1          1
4       0          0
5       1          1
6       0          0
7       0          0
8       0          0
9       0          0